FROM postgres:10.14-alpine

# environment:
#   - POSTGRES_USER=${DB_USER}
#   - POSTGRES_PASSWORD=${DB_PASSWORD}
# volumes:
#   - 'db:/var/lib/postgresql/data'
#   - '/tmp:/tmp'
# expose:
#   - "${DB_PORT}"
# ports:
#   - "${DB_PORT}:5432"